### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by grigio** [ideasman42/nerd-dictation#101]
it seems it can't find cffi

```
./nerd-dictation begin
Traceback (most recent call last):
  File "/home/grigio/Code/nerd-dictation/./nerd-dictation", line 1973, in <module>
    main()
  File "/home/grigio/Code/nerd-dictation/./nerd-dictation", line 1969, in main
    args.func(args)
  File "/home/grigio/Code/nerd-dictation/./nerd-dictation", line 1834, in <lambda>
    func=lambda args: main_begin(
  File "/home/grigio/Code/nerd-dictation/./nerd-dictation", line 1436, in main_begin
    found_any = text_from_vosk_pipe(
  File "/home/grigio/Code/nerd-dictation/./nerd-dictation", line 956, in text_from_vosk_pipe
    import vosk  # type: ignore
  File "/home/grigio/.local/lib/python3.9/site-packages/vosk/__init__.py", line 4, in <module>
    from .vosk_cffi import ffi as _ffi
  File "/home/grigio/.local/lib/python3.9/site-packages/vosk/vosk_cffi.py", line 2, in <module>
    import _cffi_backend
ModuleNotFoundError: No module named '_cffi_backend'

python --version
Python 3.9.10
```

**Comment by grigio** [comment]
it seems fixed closing and reopening the terminal
