### ISSUE TITLE
subprocess.CalledProcessError: Command ... died with <Signals.SIGABRT: 6>. (broken pipe)

### ISSUE THREAD

**Issue by Tom-Obvious** [ideasman42/nerd-dictation#70]
Hi ideasman42,

I want to try out nerd-dictation because it looks like an awesome tool, so I installed it on my Framework-Laptop running with Fedora-Linux.
Because of Wayland, I installed ydotool too.

After executing this command => ./nerd-dictation begin --simulate-input-tool=YDOTOOL --vosk-model-dir=./model &
The programm crashes after the first word.
This is the error message: 

failed to connect socket: No such file or directory
Traceback (most recent call last):
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 1574, in <module>
    main()
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 1570, in main
    args.func(args)
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 1492, in <lambda>
    func=lambda args: main_begin(
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 1203, in main_begin
    found_any = text_from_vosk_pipe(
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 1006, in text_from_vosk_pipe
    handle_fn_wrapper(text, True)
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 943, in handle_fn_wrapper
    handle_fn(len(text_prev) - match, text_curr[match:])
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 197, in simulate_typing_with_ydotool
    run_command_or_exit_on_failure(
  File "/home/tom/Entwicklung/Python/Dictation/nerd-dictation/./nerd-dictation", line 50, in run_command_or_exit_on_failure
    subprocess.check_output(cmd)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ydotool', 'type', '--next-delay', '1', '--', 'test']' died with <Signals.SIGABRT: 6>.
write() fehlgeschlagen: Datenübergabe unterbrochen (broken pipe)

What could be the problem or how could I fix it?

Thanks in advance for your answer!

Tom

**Comment by ideasman42** [comment]
Hi, in these cases it's best to get `ydotool` working in isolation.

This command should type hello.

`ydotool type hello`

Once this works on the command line, it should also work from `nerd-dictation`.
If for some reason `ydotool` is giving you a lot of trouble, you could try `wtype` too.

**Comment by ElSamiru** [comment]
Hey @Tom-Obvious did you fixed the issue ?

**Comment by Tom-Obvious** [comment]
Sorry, for writing this late.
I... um 'fixed' the issue!
Ydotool did't run properly as root, so... the solution was rather simple!

With the following tree commands, I changed the permission,
started the ydotool demon and started successfully nerd-dictation.

**sudo chmod u+s /usr/bin/ydotool**
**ydotoold &**
**./nerd-dictation begin --simulate-input-tool=YDOTOOL --vosk-model-dir=./model &**
